trigger:
  branches:
    include:
      - 'master'

# Different users have different machine setups, we run the build three times, on ubuntu, osx, and windows
strategy:
  matrix:
    linux:
      imageName: "ubuntu-16.04"
    mac:
      imageName: "macos-10.14"
    windows:
      imageName: "vs2017-win2016"
  maxParallel: 3

pool:
  vmImage: $(imageName)

variables:
  currentImage: $(imageName)
  VERSION:

steps:
  # This task pulls the <version> value from the pom.xml file, so we can set it to the variable $version.
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        [xml]$pomXml = Get-Content .\pom.xml
        # version
        Write-Host $pomXml.project.version
        $version=$pomXml.project.version
        Write-Host "##vso[task.setvariable variable=version]$version"

  # Runs 'mvn package'
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'

  # Prints out the build version, for debugging purposes
  - bash: echo Pulled version from pom.xml => $(version)

  # Copies the generated *.jar file to the staging directory, mainly for debugging purposes
  - task: CopyFiles@2
    condition: eq(variables.currentImage, 'ubuntu-16.04')
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      SourceFolder: '$(system.defaultworkingdirectory)'
      Contents: "$(System.DefaultWorkingDirectory)/target/fhir-test-cases-$(version).jar"
      TargetFolder: '$(build.artifactstagingdirectory)'

  # Azure pipelines cannot pass variables between pipelines, but it can pass files, so we
  # pass the build id (ex: 1.1.13-SNAPSHOT) as a string in a file. This used to be used for
  # the nexus upload tool, but we no longer use the stock tool. This is only here for debugging
  # now, and to remind me of how sad I was when I was trying to get this to work.
  - bash: |
      echo $(version)
      VERSION=$(version)
      echo "$VERSION" > $(System.DefaultWorkingDirectory)/VERSION
    condition: eq(variables.currentImage, 'ubuntu-16.04')

  # Copies the VERSION file containing the build id (ex: 1.1.13-SNAPSHOT) to the staging directory
  - task: CopyFiles@2
    condition: eq(variables.currentImage, 'ubuntu-16.04')
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      SourceFolder: '$(System.Defaultworkingdirectory)'
      Contents: "$(System.DefaultWorkingDirectory)/VERSION"
      TargetFolder: '$(build.artifactstagingdirectory)'

  # Publishes the files we've moved into the staging directory, so they can be accessed by the 
  # release pipeline. You will notice that we only do this for the ubuntu build, as doing it 
  # for each of the three release pipelines will cause conflicts.
  - task: PublishBuildArtifacts@1
    condition: eq(variables.currentImage, 'ubuntu-16.04')
    displayName: 'Publish Build Artifacts'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'